services:
  proxy:
    profiles:
      - "proxy"
      - "appstack"
    image: nginx:1.25.5-alpine
    volumes:
      - ./resources/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
  fe:
    profiles:
      - "frontend"
      - "appstack"
    image: 339712946908.dkr.ecr.ap-southeast-1.amazonaws.com/cat-fe:v2.0
    restart: always
    env_file:
      - cat-fe.env
  be:
    profiles:
      - "backend"
      - "appstack"
    image: 339712946908.dkr.ecr.ap-southeast-1.amazonaws.com/cat-be:v2.0
    restart: always
    env_file:
      - cat-be.env
    healthcheck:
      test: ["CMD", "curl", "localhost:8000/api/healthcheck"]
      timeout: 20s
      retries: 10
  migration:
    profiles:
      - "migration"
    image: 339712946908.dkr.ecr.ap-southeast-1.amazonaws.com/cat-be:v2.0
    command: flask db upgrade
    env_file:
      - cat-be.env
